version: '3.8'
services:
  db:
    image: mysql:latest
    container_name: mysql
    cpus: 3
    ports:
      - "3306:3306"
    volumes:
      - db_data:/home/benaventi/Documents/projects/bases1/proyecto2
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    restart: unless-stopped

volumes:
  db_data:

  
  

